### ISSUE TITLE
I keep getting this error when I run Main

### ISSUE THREAD

**Issue by MSAL90** [Philipinho/GetVideoBot#2]
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:373)
	at java.base/java.util.ArrayList.get(ArrayList.java:426)
	at Bot.findMentions(Bot.java:58)
	at Run.StartApplication(Run.java:17)
	at Main.main(Main.java:4)

**Comment by Philipinho** [comment]
#3
