### ISSUE TITLE
I keep getting this error when I run Main

### ISSUE THREAD

**Issue by MSAL90** [Philipinho/GetVideoBot#3]
`Exception in thread "main" java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:373)
	at java.base/java.util.ArrayList.get(ArrayList.java:426)
	at Bot.findMentions(Bot.java:58)
	at Run.StartApplication(Run.java:17)
	at Main.main(Main.java:4)`

**Comment by MSAL90** [comment]
it ran successfully at first. but now it won't work and keep giving me this error

**Comment by Philipinho** [comment]
Have you tweeted at least once on the Twitter account?

**Comment by MSAL90** [comment]
No, it worked when I tweeted :). thank you Philip

**Comment by MSAL90** [comment]
After I ran it successfully, it runs for about 50 seconds and stops. it gives me this code: `TwitterException{exceptionCode=[feaf0090-0a41636f], statusCode=429, message=Rate limit exceeded, code=88, retryAfter=-1, rateLimitStatus=RateLimitStatusJSONImpl{remaining=0, limit=75, resetTimeInSeconds=1587590544, secondsUntilReset=852}, version=4.0.7}
`
Therefore, I have to wait 10 minutes to run it again. what can i do to avoid this?
